>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> a = BaseGeometry()

# Check if 'a' is an instance of BaseGeometry
>>> isinstance(a, BaseGeometry)
True

# Validate a positive integer
>>> a.integer_validator("width", 2)

# Call the area method and check that it raises an exception
>>> a.area()
Traceback (most recent call last):
Exception: area() is not implemented

# Validate a value equal to zero
>>> a.integer_validator("width", 0)
Traceback (most recent call last):
ValueError: width must be greater than 0

# Validate a negative value
>>> a.integer_validator("width", -5)
Traceback (most recent call last):
ValueError: width must be greater than 0

>>> a.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> a.integer_validator("width")
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

# Validate an incorrect data type (string)
>>> a.integer_validator("width", "a")
Traceback (most recent call last):
TypeError: width must be an integer

# Validate an incorrect data type (tuple)
>>> a.integer_validator("age", (7,))
Traceback (most recent call last):
TypeError: age must be an integer

# Validate an incorrect data type (list)
>>> a.integer_validator("age", [3])
Traceback (most recent call last):
TypeError: age must be an integer

# Validate an incorrect data type (boolean)
>>> a.integer_validator("age", False)
Traceback (most recent call last):
TypeError: age must be an integer

# Validate an incorrect data type (set)
>>> a.integer_validator("age", {3, 4})
Traceback (most recent call last):
TypeError: age must be an integer

# Validate an incorrect data type (None)
>>> a.integer_validator("age", None)
Traceback (most recent call last):
TypeError: age must be an integer

# Validate an incorrect data type (float)
>>> a.integer_validator("age", 5.54)
Traceback (most recent call last):
TypeError: age must be an integer

# Validate an incorrect data type
>>> a.integer_validator("age", "4")
Traceback (most recent call last):
TypeError: age must be an integer